### ISSUE TITLE
FastAI.jl tabular development GSoC tracking

### ISSUE THREAD

**Issue by manikyabard** [FluxML/ML-Coordination-Tracker#34]
These points include implementation, tests and required documentation.

## Data
- [x] [Container](https://github.com/FluxML/FastAI.jl/pull/26)
- [x] [Transforms](https://github.com/lorenzoh/DataAugmentation.jl/pull/45)
    - Normalize
    - Categorify
    - Fill Missing

## Model and Training
- [x] [Model Architecture](https://github.com/FluxML/FastAI.jl/pull/124)

## Learning Methods
These would include implementing the interface defined [here](https://fluxml.ai/FastAI.jl/dev/docs/interfaces.md.html#learning-method-interfaces). 
- [x] [Regression](https://github.com/FluxML/FastAI.jl/pull/141)
- [x] [Classification](https://github.com/FluxML/FastAI.jl/pull/141)

**Comment by darsnack** [comment]
Closing this as done
